name: cards_party
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  auto_route: ^7.8.0
  bloc: ^8.1.2
  equatable: ^2.0.5
  firebase_core: ^2.27.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_guid: ^0.3.1
  flutter_localizations:
    sdk: flutter
  game_repository:
    path: packages/game_repository
  hydrated_bloc: ^9.1.2
  intl: ^0.18.0
  lobby_repository:
    path: packages/lobby_repository
  path_provider: ^2.1.1
  rules_repository:
    path: packages/rules_repository

dev_dependencies:
  auto_route_generator: ^7.3.1
  bloc_test: ^9.1.2
  build_runner: ^2.4.6
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.0
  very_good_analysis: ^5.0.0

flutter:
  uses-material-design: true
  generate: true
