// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show TargetPlatform, defaultTargetPlatform, kIsWeb;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCGpL8DTbiwOqs7CV3sru2GcfTBFYHUH6E',
    appId: '1:51250481610:web:05d9ac7a55c55bdc91e733',
    messagingSenderId: '51250481610',
    projectId: 'cardspartydev',
    authDomain: 'cardspartydev.firebaseapp.com',
    databaseURL: 'https://cardspartydev-default-rtdb.firebaseio.com',
    storageBucket: 'cardspartydev.appspot.com',
    measurementId: 'G-35L2MF34NW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDyiN-Pke0sUzQfMqhF1jowRkcbY0WALv4',
    appId: '1:51250481610:android:bc5e4d46879bdbc791e733',
    messagingSenderId: '51250481610',
    projectId: 'cardspartydev',
    databaseURL: 'https://cardspartydev-default-rtdb.firebaseio.com',
    storageBucket: 'cardspartydev.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBEFhS_B30cFHa16z-IdJP_JFWmC4bgA4A',
    appId: '1:51250481610:ios:fbc4e4b03a741f1791e733',
    messagingSenderId: '51250481610',
    projectId: 'cardspartydev',
    databaseURL: 'https://cardspartydev-default-rtdb.firebaseio.com',
    storageBucket: 'cardspartydev.appspot.com',
    iosBundleId: 'com.example.verygoodcore.cards-party',
  );
}
