name: rule_interpreter
description: Provides logic for interpreting rules using a composite tree pattern
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dev_dependencies:
  mocktail: ^1.0.0
  test: ^1.19.2
  very_good_analysis: ^5.1.0

dependencies:
  game_repository:
    path: ../game_repository
  rules_repository:
    path: ../rules_repository
